In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import torch

import napari

from tqdm import tqdm

In [ ]:
def read_data_and_levels(folder):
    data = np.load(folder + '/data.npy')
    data[data < 0] = 0
    levels = np.load(folder + '/levels.npy')
    return data , levels

In [ ]:
def create_mask(upper_layer, second_layer):
    mask = np.zeros((256, 512, 512), dtype=int)
    for x in range(512):
        for y in range(512):
            z1 = upper_layer[x, y]
            z2 = second_layer[x, y]
            mask[int(z1):int(z2), y, x] = 1
    return mask

In [ ]:
def cutted_array(data, masks, start, end):
    return data[:, :, start:end], masks[:, :, :, start:end]

In [ ]:
def from_levels_to_masks(levels):
    masks = np.zeros((5, 256, 512, 512), dtype=int)
    zero_level = np.zeros((512, 512))
    last_level = np.ones((512, 512)) * 255
    masks[0] = create_mask(zero_level, levels[0])
    masks[1] = create_mask(levels[0], levels[1])
    masks[2] = create_mask(levels[1], levels[2])
    masks[3] = create_mask(levels[2], levels[3])
    masks[4] = create_mask(levels[3], last_level)
    return masks

In [ ]:
def DICE_COE(mask1, mask2):
    intersect = np.sum(mask1*mask2)
    fsum = np.sum(mask1)
    ssum = np.sum(mask2)
    dice = (2 * intersect ) / (fsum + ssum)
    # dice = round(dice, 3) # for easy reading
    return dice

In [ ]:
def viewer_data(data, masks):
    viewer = napari.view_image(data, name='3D Image', colormap='afmhot', contrast_limits = (15,  41))
    colors = np.linspace(
        start=[1, 1, 1, 1],
        stop=[0, 1, 0, 1],
        num=10,
        endpoint=True
    )
    colors[0] = np.array([1., 1., 1., 0])
    new_colormap = {
      'colors': colors,
      'name': 'white_to_green',
      'interpolation': 'linear'
    }

    for i in range(5):
        viewer.add_image(masks[i], name='Segmentation Mask', colormap=new_colormap, opacity=0.3)
    napari.run()

This is not done in a loop, as it is important to visualize and review it in person in napari:

### Finger 5 (Nika)

In [ ]:
data, levels = read_data_and_levels('C:/Users/MK/Nika/размеченные датасеты/finger5')
masks = from_levels_to_masks(levels)
data, masks = cutted_array(data, masks, 156, 156+256)

In [ ]:
num_array = 5
num_model = 0

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99620216 0.82791241 0.74384209 0.7208457  0.97981774]
0.853724022167366


In [ ]:
num_model = 1

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99620653 0.84096388 0.90227014 0.85376593 0.98591299]
0.9158238924194663


In [ ]:
num_model = 2

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.98425693 0.86586063 0.87417823 0.80102087 0.97790004]
0.9006433405120026


In [ ]:
num_model = 3

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99586764 0.82546666 0.89059657 0.83564675 0.97921923]
0.9053593712649086


In [ ]:
num_model = 4

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.9960993  0.86838172 0.82800118 0.78674533 0.98533959]
0.8929134250058709


### Finger0 (Mikel)

In [ ]:
data, levels = read_data_and_levels('C:/Users/MK/Nika/размеченные датасеты/finger6')
masks = from_levels_to_masks(levels)
data, masks = cutted_array(data, masks, 60, 60+256)

In [ ]:
num_array = 6
num_model = 0

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99389829 0.95779201 0.97367052 0.90384217 0.97815079]
0.9614707567943876


In [ ]:
num_model = 1

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99377793 0.95919986 0.97732937 0.9302092  0.9855632 ]
0.9692159135307452


In [ ]:
num_model = 2

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99460469 0.96052736 0.96754273 0.89829632 0.97736775]
0.9596677708959798


In [ ]:
num_model = 3

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99405809 0.95951372 0.97689568 0.91431935 0.98002485]
0.9649623361549118


In [ ]:
num_model = 4

In [ ]:
masks_model = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/val/masks_model'
                          + str(num_array) + '_' + str(num_model) + '.npy')

In [ ]:
viewer_data(data, masks_model)

In [ ]:
dice = np.zeros(5)
for i in range(5):
    dice[i] = DICE_COE(masks[i], masks_model[i])
print(dice)
print(np.mean(dice))

[0.99494012 0.96218752 0.97833814 0.92421481 0.98259906]
0.9684559306266518


## Calculate the average for 1 model

In [ ]:
dice1 = [[0.99620653, 0.84096388, 0.90227014, 0.85376593, 0.98591299],
         [0.99377793, 0.95919986, 0.97732937, 0.9302092,  0.9855632 ]]

In [ ]:
dice1 = np.array(dice2)

In [ ]:
dice1.mean(axis = 0)

array([0.99499223, 0.90008187, 0.93979976, 0.89198756, 0.98573809])

# Number of epochs at each cross-validation step

In [ ]:
def show_min_and_argmin_epoch(num_model):
    losses_test = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/losses_test' + str(num_model) + '.npy')
    print(num_model, ': min loss', np.min(losses_test))
    print(num_model, ': argmin loss',np.argmin(losses_test))

In [ ]:
def show_min_and_argmin_epoch_train(num_model):
    losses_train = np.load('C:/Users/MK/Nika/2D/exp1/hyperparameter0/losses_train' + str(num_model) + '.npy')
    print(num_model, ': min loss', np.min(losses_train))
    print(num_model, ': argmin loss',np.argmin(losses_train))

In [ ]:
for i in range(5):
    show_min_and_argmin_epoch(i)

0 : min loss 0.15221190758165903
0 : argmin loss 0
1 : min loss 0.18455353693570942
1 : argmin loss 0
2 : min loss 0.08295096243091393
2 : argmin loss 1
3 : min loss 0.08129526463744696
3 : argmin loss 3
4 : min loss 0.06562163541093469
4 : argmin loss 2


In [ ]:
for i in range(5):
    show_min_and_argmin_epoch_train(i)

0 : min loss 0.006675044743360559
0 : argmin loss 39
1 : min loss 0.006324663155737653
1 : argmin loss 39
2 : min loss 0.006697344508211245
2 : argmin loss 39
3 : min loss 0.006813125468852377
3 : argmin loss 39
4 : min loss 0.006812963859374577
4 : argmin loss 39
